# Generated by Django 6.0.4 on 2026-09-07 18:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import runs.domain.lifecycle.states
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongestionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('congestion_level', models.CharField(blank=True, choices=[('UNKNOWN_CONGESTION_LEVEL', 'Nivel de congestión desconocido'), ('RUNNING_SMOOTHLY', 'Tráfico fluido'), ('STOP_AND_GO', 'Tráfico fluctuante'), ('CONGESTION', 'Congestión'), ('SEVERE_CONGESTION', 'Congestión severa')], max_length=100, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='OccupancyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('occupancy_status', models.CharField(blank=True, choices=[('EMPTY', 'Vacío'), ('MANY_SEATS_AVAILABLE', 'Muchos asientos disponibles'), ('FEW_SEATS_AVAILABLE', 'Pocos asientos disponibles'), ('STANDING_ROOM_ONLY', 'Solo espacio de pie'), ('CRUSHED_STANDING_ROOM_ONLY', 'Solo espacio de pie apretado'), ('FULL', 'Lleno'), ('NOT_ACCEPTING_PASSENGERS', 'No acepta pasajeros'), ('NO_DATA_AVAILABLE', 'No hay datos disponibles'), ('NOT_BOARDABLE', 'No es posible abordar este tipo de vehículo')], max_length=100, null=True)),
                ('occupancy_percentage', models.IntegerField(blank=True, null=True)),
                ('occupancy_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_wheelchair_accesible', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('WHEELCHAIR_ACCESIBLE', 'Accesible para silla de ruedas'), ('WHEELCHAIR_INACCESIBLE', 'No accesible para silla de ruedas')], max_length=100, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('bearing', models.FloatField(blank=True, null=True)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('route_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_id', models.CharField(blank=True, max_length=100, null=True)),
                ('direction_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DurationField(blank=True, null=True)),
                ('schedule_relationship', models.CharField(blank=True, choices=[('SCHEDULED', 'Scheduled in GTFS'), ('ADDED', 'Added to schedule'), ('UNSCHEDULED', 'Unscheduled'), ('CANCELED', 'Canceled'), ('DUPLICATED', 'Duplicated'), ('DELETED', 'Deleted')], max_length=100, null=True)),
                ('run_lifecycle_state', models.CharField(blank=True, choices=runs.domain.lifecycle.states.choices, default=runs.domain.lifecycle.states.RunLifecycleStates['REQUESTED'], max_length=40, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ManyToManyField(blank=True, to='operations.operator')),
                ('vehicle', models.ManyToManyField(blank=True, to='operations.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_stop_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('stop_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('INCOMING_AT', 'Llegando a la parada'), ('STOPPED_AT', 'Detenido en la parada'), ('IN_TRANSIT_TO', 'En tránsito a la parada')], max_length=100, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RunLifecycleTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=128)),
                ('from_state', models.CharField(max_length=64, null=True)),
                ('to_state', models.CharField(max_length=64, null=True)),
                ('guards', models.JSONField(blank=True, default=dict, null=True)),
                ('actions', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.run')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'timestamp'], name='runs_runlif_run_id_92ecb6_idx'), models.Index(fields=['event_name'], name='runs_runlif_event_n_d616c7_idx')],
            },
        ),
    ]
