mqtt {
    allow_anonymous = true
    max_packet_size = 10KB
    msq_len = 2048
    qos_duration = 10s
    keepalive_backoff = 1250
    max_inflight_window = 2048
    max_awaiting_rel = 10
    await_rel_timeout = 10s
}

listeners.tcp {
    bind = "0.0.0.0:1883"
}

log {
    to = [console]
    level = warn
}
