[project]
name = "databus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "celery[librabbitmq]>=5.6.3",
    "channels>=4.3.1",
    "channels-redis>=4.3.0",
    "daphne>=4.2.1",
    "django==6.0.4",
    "django-celery-beat>=2.8.1",
    "django-celery-results>=2.6.0",
    "django-filter>=25.1",
    "djangorestframework>=3.16.1",
    "djangorestframework-gis>=1.2.0",
    "drf-spectacular>=0.28.0",
    "flower>=2.0.1",
    "geopandas>=1.1.1",
    "gtfs-django",
    "gtfs-io",
    "gtfs-realtime-bindings>=1.0.0",
    "gunicorn>=23.0.0",
    "kombu>=5.6.2",
    "mkdocs-material>=9.6.18",
    "paho-mqtt>=2.1.0",
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "prefect>=3.6.12",
    "psycopg2-binary>=2.9.11",
    "python-decouple>=3.8",
    "redis>=6.4.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.0.0",
    "pytest>=8.4.1",
    "pytest-django>=4.11.1",
    "ruff>=0.12.11",
    "watchfiles>=0.24.0",
]

[tool.uv.workspace]
members = [
    "gtfs-io",
    "gtfs-django",
]

[tool.uv.sources]
gtfs-io = { workspace = true, editable = true }
gtfs-django = { workspace = true, editable = true }
