# Generated by Django 6.0.4 on 2026-04-15 04:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gtfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('agency', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtfs.agency')),
            ],
        ),
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='data-providers/')),
                ('company', models.ManyToManyField(blank=True, to='periodic_engine.company')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=100, null=True)),
                ('provides_vehicle', models.BooleanField(default=False)),
                ('provides_operator', models.BooleanField(default=False)),
                ('provides_run', models.BooleanField(default=False)),
                ('provides_position', models.BooleanField(default=False)),
                ('provides_progression', models.BooleanField(default=False)),
                ('provides_occupancy', models.BooleanField(default=False)),
                ('provides_conditions', models.BooleanField(default=False)),
                ('provides_emissions', models.BooleanField(default=False)),
                ('provides_travelers', models.BooleanField(default=False)),
                ('provides_authorizations', models.BooleanField(default=False)),
                ('provides_fares', models.BooleanField(default=False)),
                ('provides_transfers', models.BooleanField(default=False)),
                ('provides_alerts', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.dataprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='operators/')),
                ('company', models.ManyToManyField(to='periodic_engine.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(max_length=31)),
                ('wheelchair_accessible', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('WHEELCHAIR_ACCESIBLE', 'Accesible para silla de ruedas'), ('WHEELCHAIR_INACCESIBLE', 'No accesible para silla de ruedas')], max_length=100, null=True)),
                ('wifi', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible')], max_length=100, null=True)),
                ('air_conditioning', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible')], max_length=100, null=True)),
                ('mobile_charging', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible')], max_length=100, null=True)),
                ('bike_rack', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible')], max_length=100, null=True)),
                ('has_screen', models.BooleanField(default=False)),
                ('has_headsign_screen', models.BooleanField(default=False)),
                ('has_audio', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('IN_SERVICE', 'En servicio'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('SOLD', 'Vendido'), ('ON_FIRE', 'En llamas')], max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periodic_engine.company')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_id', models.CharField(blank=True, max_length=100, null=True)),
                ('direction_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DurationField(blank=True, null=True)),
                ('schedule_relationship', models.CharField(blank=True, choices=[('SCHEDULED', 'Agendado'), ('ADDED', 'Agregado'), ('UNSCHEDULED', 'No agendado'), ('CANCELED', 'Cancelado'), ('DUPLICATED', 'Duplicado'), ('DELETED', 'Borrado')], max_length=100, null=True)),
                ('run_status', models.CharField(blank=True, choices=[('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('INTERRUPTED', 'Interrumpido')], max_length=40, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periodic_engine.operator')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_stop_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('stop_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('INCOMING_AT', 'Llegando a la parada'), ('STOPPED_AT', 'Detenido en la parada'), ('IN_TRANSIT_TO', 'En tránsito a la parada')], max_length=100, null=True)),
                ('congestion_level', models.CharField(blank=True, choices=[('UNKNOWN_CONGESTION_LEVEL', 'Nivel de congestión desconocido'), ('RUNNING_SMOOTHLY', 'Tráfico fluido'), ('STOP_AND_GO', 'Tráfico fluctuante'), ('CONGESTION', 'Congestión'), ('SEVERE_CONGESTION', 'Congestión severa')], max_length=100, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('bearing', models.FloatField(blank=True, null=True)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('occupancy_status', models.CharField(blank=True, choices=[('EMPTY', 'Vacío'), ('MANY_SEATS_AVAILABLE', 'Muchos asientos disponibles'), ('FEW_SEATS_AVAILABLE', 'Pocos asientos disponibles'), ('STANDING_ROOM_ONLY', 'Solo espacio de pie'), ('CRUSHED_STANDING_ROOM_ONLY', 'Solo espacio de pie apretado'), ('FULL', 'Lleno'), ('NOT_ACCEPTING_PASSENGERS', 'No acepta pasajeros'), ('NO_DATA_AVAILABLE', 'No hay datos disponibles'), ('NOT_BOARDABLE', 'No es posible abordar este tipo de vehículo')], max_length=100, null=True)),
                ('occupancy_percentage', models.IntegerField(blank=True, null=True)),
                ('occupancy_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_wheelchair_accesible', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('WHEELCHAIR_ACCESIBLE', 'Accesible para silla de ruedas'), ('WHEELCHAIR_INACCESIBLE', 'No accesible para silla de ruedas')], max_length=100, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=100, null=True)),
                ('provides_vehicle', models.BooleanField(default=False)),
                ('provides_operator', models.BooleanField(default=False)),
                ('provides_run', models.BooleanField(default=False)),
                ('provides_position', models.BooleanField(default=False)),
                ('provides_progression', models.BooleanField(default=False)),
                ('provides_occupancy', models.BooleanField(default=False)),
                ('provides_conditions', models.BooleanField(default=False)),
                ('provides_emissions', models.BooleanField(default=False)),
                ('provides_travelers', models.BooleanField(default=False)),
                ('provides_authorizations', models.BooleanField(default=False)),
                ('provides_fares', models.BooleanField(default=False)),
                ('provides_transfers', models.BooleanField(default=False)),
                ('provides_alerts', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('data_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.dataprovider')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.equipment')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodic_engine.vehicle'),
        ),
    ]
