# Generated by Django 6.0.4 on 2026-09-07 18:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='data-providers/')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('legal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('linked_agency', models.ManyToManyField(blank=True, to='feed.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.dataprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='operators/')),
                ('is_driver', models.BooleanField(default=False)),
                ('is_dispatcher', models.BooleanField(default=False)),
                ('is_administrator', models.BooleanField(default=False)),
                ('company', models.ManyToManyField(to='operations.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('provides_vehicle', models.BooleanField(default=False)),
                ('provides_operator', models.BooleanField(default=False)),
                ('provides_run', models.BooleanField(default=False)),
                ('provides_position', models.BooleanField(default=False)),
                ('provides_progression', models.BooleanField(default=False)),
                ('provides_occupancy', models.BooleanField(default=False)),
                ('provides_conditions', models.BooleanField(default=False)),
                ('provides_emissions', models.BooleanField(default=False)),
                ('provides_travelers', models.BooleanField(default=False)),
                ('provides_authorizations', models.BooleanField(default=False)),
                ('provides_fares', models.BooleanField(default=False)),
                ('provides_transfers', models.BooleanField(default=False)),
                ('provides_alerts', models.BooleanField(default=False)),
                ('source_type', models.CharField(blank=True, choices=[('mqtt', 'MQTT'), ('http', 'HTTP'), ('both', 'Both')], max_length=16, null=True)),
                ('source_http_url', models.URLField(blank=True, null=True)),
                ('source_json_mapping', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(max_length=31)),
                ('wheelchair_accessible', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('WHEELCHAIR_ACCESIBLE', 'Accesible para silla de ruedas'), ('WHEELCHAIR_INACCESIBLE', 'No accesible para silla de ruedas')], max_length=100, null=True)),
                ('wifi', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible')], max_length=100, null=True)),
                ('air_conditioning', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible')], max_length=100, null=True)),
                ('mobile_charging', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible')], max_length=100, null=True)),
                ('bike_rack', models.CharField(blank=True, choices=[('NO_VALUE', 'No hay información'), ('UNKNOWN', 'Desconocido'), ('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible')], max_length=100, null=True)),
                ('has_screen', models.BooleanField(default=False)),
                ('has_headsign_screen', models.BooleanField(default=False)),
                ('has_audio', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('IN_SERVICE', 'En servicio'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('ON_FIRE', 'En llamas')], max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.company')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.dataprovider')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.equipment')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.vehicle'),
        ),
    ]
