# Generated by Django 6.0.4 on 2026-07-21 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='provides_alerts',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_authorizations',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_conditions',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_emissions',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_fares',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_occupancy',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_operator',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_position',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_progression',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_run',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_transfers',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_travelers',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='provides_vehicle',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_alerts',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_authorizations',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_conditions',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_emissions',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_fares',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_occupancy',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_operator',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_position',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_progression',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_run',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_transfers',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_travelers',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='provides_vehicle',
        ),
        migrations.AddField(
            model_name='company',
            name='legal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_dispatcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='company',
            name='linked_agency',
        ),
        migrations.AlterField(
            model_name='equipmentlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_SERVICE', 'En servicio'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('ON_FIRE', 'En llamas')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('provides_vehicle', models.BooleanField(default=False)),
                ('provides_operator', models.BooleanField(default=False)),
                ('provides_run', models.BooleanField(default=False)),
                ('provides_position', models.BooleanField(default=False)),
                ('provides_progression', models.BooleanField(default=False)),
                ('provides_occupancy', models.BooleanField(default=False)),
                ('provides_conditions', models.BooleanField(default=False)),
                ('provides_emissions', models.BooleanField(default=False)),
                ('provides_travelers', models.BooleanField(default=False)),
                ('provides_authorizations', models.BooleanField(default=False)),
                ('provides_fares', models.BooleanField(default=False)),
                ('provides_transfers', models.BooleanField(default=False)),
                ('provides_alerts', models.BooleanField(default=False)),
                ('source_type', models.CharField(blank=True, choices=[('mqtt', 'MQTT'), ('http', 'HTTP'), ('both', 'Both')], max_length=16, null=True)),
                ('source_http_url', models.URLField(blank=True, null=True)),
                ('source_json_mapping', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='linked_agency',
            field=models.ManyToManyField(blank=True, to='feed.agency'),
        ),
    ]
